"""Option helpers for UniFi Network Infrastructure."""

from __future__ import annotations

from homeassistant.config_entries import ConfigEntry

from .const import (
    CONF_ENABLE_FIREWALL_POLICY_CONTROLS,
    CONF_ENABLE_LOCATE_CONTROL,
    CONF_ENABLE_GUEST_WIFI_CONTROLS,
    CONF_ENABLE_INTERFACE_CONTROLS,
    CONF_ENABLE_POE_CONTROLS,
    CONF_ENABLE_POE_RESET,
    CONF_ENABLE_PORT_FORWARD_CONTROLS,
    CONF_ENABLE_PORT_ADMIN_CONTROLS,
    CONF_ENABLE_PORT_BOUNCE,
    CONF_ENABLE_PORT_PROTECTION,
    CONF_ENABLE_REBOOT_CONTROL,
    CONF_ENABLE_ROUTE_POLICY_CONTROLS,
    CONF_ENABLE_WIFI_CONTROLS,
    CONF_SCAN_INTERVAL,
    DEFAULT_ENABLE_FIREWALL_POLICY_CONTROLS,
    DEFAULT_ENABLE_LOCATE_CONTROL,
    DEFAULT_ENABLE_GUEST_WIFI_CONTROLS,
    DEFAULT_ENABLE_INTERFACE_CONTROLS,
    DEFAULT_ENABLE_POE_CONTROLS,
    DEFAULT_ENABLE_POE_RESET,
    DEFAULT_ENABLE_PORT_FORWARD_CONTROLS,
    DEFAULT_ENABLE_PORT_ADMIN_CONTROLS,
    DEFAULT_ENABLE_PORT_BOUNCE,
    DEFAULT_ENABLE_PORT_PROTECTION,
    DEFAULT_ENABLE_REBOOT_CONTROL,
    DEFAULT_ENABLE_ROUTE_POLICY_CONTROLS,
    DEFAULT_ENABLE_WIFI_CONTROLS,
)

OPTION_DEFAULTS = {
    CONF_ENABLE_PORT_PROTECTION: DEFAULT_ENABLE_PORT_PROTECTION,
    CONF_ENABLE_WIFI_CONTROLS: DEFAULT_ENABLE_WIFI_CONTROLS,
    CONF_ENABLE_GUEST_WIFI_CONTROLS: DEFAULT_ENABLE_GUEST_WIFI_CONTROLS,
    CONF_ENABLE_PORT_FORWARD_CONTROLS: DEFAULT_ENABLE_PORT_FORWARD_CONTROLS,
    CONF_ENABLE_ROUTE_POLICY_CONTROLS: DEFAULT_ENABLE_ROUTE_POLICY_CONTROLS,
    CONF_ENABLE_FIREWALL_POLICY_CONTROLS: DEFAULT_ENABLE_FIREWALL_POLICY_CONTROLS,
    CONF_ENABLE_INTERFACE_CONTROLS: DEFAULT_ENABLE_INTERFACE_CONTROLS,
    CONF_ENABLE_PORT_ADMIN_CONTROLS: DEFAULT_ENABLE_PORT_ADMIN_CONTROLS,
    CONF_ENABLE_POE_CONTROLS: DEFAULT_ENABLE_POE_CONTROLS,
    CONF_ENABLE_PORT_BOUNCE: DEFAULT_ENABLE_PORT_BOUNCE,
    CONF_ENABLE_POE_RESET: DEFAULT_ENABLE_POE_RESET,
    CONF_ENABLE_LOCATE_CONTROL: DEFAULT_ENABLE_LOCATE_CONTROL,
    CONF_ENABLE_REBOOT_CONTROL: DEFAULT_ENABLE_REBOOT_CONTROL,
}

CONTROL_OPTION_KEYS = (
    CONF_ENABLE_WIFI_CONTROLS,
    CONF_ENABLE_GUEST_WIFI_CONTROLS,
    CONF_ENABLE_PORT_FORWARD_CONTROLS,
    CONF_ENABLE_ROUTE_POLICY_CONTROLS,
    CONF_ENABLE_FIREWALL_POLICY_CONTROLS,
    CONF_ENABLE_INTERFACE_CONTROLS,
    CONF_ENABLE_PORT_ADMIN_CONTROLS,
    CONF_ENABLE_POE_CONTROLS,
    CONF_ENABLE_PORT_BOUNCE,
    CONF_ENABLE_POE_RESET,
    CONF_ENABLE_LOCATE_CONTROL,
    CONF_ENABLE_REBOOT_CONTROL,
)


def option_enabled(entry: ConfigEntry, key: str) -> bool:
    """Return whether an optional feature is enabled."""
    return bool(entry.options.get(key, OPTION_DEFAULTS[key]))


def monitoring_options(scan_interval: int) -> dict[str, bool | int]:
    """Return monitoring-only options with all write controls off."""
    options: dict[str, bool | int] = {
        CONF_SCAN_INTERVAL: scan_interval,
        CONF_ENABLE_PORT_PROTECTION: DEFAULT_ENABLE_PORT_PROTECTION,
    }
    options.update({key: False for key in CONTROL_OPTION_KEYS})
    return options


def port_protection_enabled(entry: ConfigEntry) -> bool:
    """Return whether port protection should be enforced."""
    return option_enabled(entry, CONF_ENABLE_PORT_PROTECTION)


def interface_controls_enabled(entry: ConfigEntry) -> bool:
    """Return whether per-interface controls should be exposed."""
    return option_enabled(entry, CONF_ENABLE_INTERFACE_CONTROLS)
